#!/usr/bin/env python3
"""Bundle data/units.json and data/model.json into data/data.js.

The page loads data.js with a plain <script> tag so it works from the local
filesystem as well as over http; fetch() of a JSON file fails under file://.
Run this after editing either JSON file.
"""
import json
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
units = json.loads((root / "data" / "units.json").read_text())
model = json.loads((root / "data" / "model.json").read_text())

out = root / "data" / "data.js"
out.write_text(
    "// Generated by tools/build_data.py -- edit the JSON files, not this one.\n"
    f"window.BH_UNITS = {json.dumps(units['units'], indent=2)};\n"
    f"window.BH_MODEL = {json.dumps(model, indent=2)};\n"
)
print(f"wrote {out.relative_to(root)} ({len(units['units'])} units)")
